### ISSUE TITLE
SideJIT {ERROR":"Could not find device!"}

### ISSUE THREAD

**Issue by jwong5087** [nythepegasus/SideJITServer#61] opened 2024-06-04 22:07 UTC
Whenever I try to run the shortcut on my phone, it keeps telling me this message. I have watched every sing SideJITServer video possible and followed all of their steps.  However, I want to know what causes this.

**Comment by Bomen9** [comment] 2024-06-05 08:25
I have been trying everything to solve the issue since last 3 days to no avail. 
Even tried creating a loop before starting SideJITServer.exe yet the error persists.

import asyncio

async def main():
    SideJITServer.exe
    pass

if __name__ == "__main__":
    # Create and run the event loop
    loop = asyncio.get_event_loop()
    try:
        loop.run_until_complete(main())
    finally:
        loop.close()

**Comment by jwong5087** [comment] 2024-06-05 21:50
do i type this in my powershell?

**Comment by Bomen9** [comment] 2024-06-06 07:58
@jwong5087 You can try to follow all the steps on discussion #59. Maybe that should solve your problem. 
Mine isn't solved yet.

**Comment by jwong5087** [comment] 2024-06-06 18:14
Yeah i tried and to no avail like u said

**Comment by Bomen9** [comment] 2024-06-07 07:58
What version of IOS are you on? My iPad air 2 won't upgrade anymore.
I am on iPad OS 15.8.2. 

Maybe that is why we are not able to use SideJIT?

**Comment by ianblankg** [comment] 2024-06-07 19:44
iPhone 12 here on OS 17, same issue, can’t find device.

**Comment by M1ke82** [comment] 2024-06-11 18:05
I'm on Ipados 17.3 and having the same issue

**Comment by Bomen9** [comment] 2024-06-12 05:33
@nythepegasus Help please?

**Comment by yohu123** [comment] 2024-06-17 16:42
I have the exact same issue. I'm using an iPhone 15 running iOS 17.5.1
I've even heard that SideJITServer works just fine on iOS 18.0 beta. You only need to repair and setup the shortcut again.
@nythepegasus Please help us.

**Comment by GermanBucket** [comment] 2024-06-17 17:10
do you have your phones connected while executing the shortcut? for me it only works if my phone has an active connection with the pc

**Comment by yohu123** [comment] 2024-06-18 04:13
Hi,

Yes, the iPhone is connected at all times right before running ‘SideJITServer —pair’ in PowerShell till the error in the shortcut.



Thanks & Regards,

Yohan Irani

________________________________

**Comment by ColinToft** [comment] 2024-06-21 21:15
Hi,

I had this same issue and I was able to resolve it by doing the following:

1. Upgraded to pymobiledevice 4.10.3. I first took out the <=4.3.0 requirement in requirements.txt, then
```pip3 install pymobiledevice3==4.10.3```
I think I had to try this twice, it errored the first time for some reason.
You can verify with `SideJITServer --version` that the pymobiledevice3 version has changed.

2. Upgraded to iOS 17.5.1, I was getting an error before with the tunnel and I think pymobiledevice3 handles tunnels differently for iOS >= 17.4

3. Then I was getting the error in #31,  which I was able to fix by running the `pymobiledevice3 mounter auto-mount --udid UDID` mentioned in that issue.

After these steps, SideJITServer seems to be working well. Hopefully this helps!

**Comment by yohu123** [comment] 2024-06-23 04:37
I have the exact same issue. I'm using an iPhone 15 running iOS 17.5.1
I've even heard that SideJITServer works just fine on iOS 18.0 beta. You only need to repair and setup the shortcut again.
@nythepegasus Please help us.

> Hi,
> 
> I had this same issue and I was able to resolve it by doing the following:
> 
>     1. Upgraded to pymobiledevice 4.10.3. I first took out the <=4.3.0 requirement in requirements.txt, then
>        `pip3 install pymobiledevice3==4.10.3`
>        I think I had to try this twice, it errored the first time for some reason.
>        You can verify with `SideJITServer --version` that the pymobiledevice3 version has changed.
> 
>     2. Upgraded to iOS 17.5.1 (from 17.3.1), I was getting an error before with the tunnel and I think pymobiledevice3 handles tunnels differently for iOS >= 17.4
> 
>     3. Then I was getting the error in [No such service: com.apple.internal.dt.remote.debugproxy #31](https://github.com/nythepegasus/SideJITServer/issues/31),  which I was able to fix by running the `pymobiledevice3 mounter auto-mount --udid UDID` mentioned in that issue.
> 
> 
> After these steps, SideJITServer seems to be working well. Hopefully this helps!

Hi @ColinToft,

Firstly, thanks for replying as all those suffering with this error had lost hope.

Secondly, I installed version 4.10.3 of pymobiledevice3 and confirmed it via 'SideJITServer --version'.

But still I get the same '{ERROR":"Could not find device!"}' message while running the SideJITServer shortcut while getting a "HTTP/1.1" 200 -" in PowerShell during pairing mode.

I wish I would have gotten your #31 error but no.

One question though, after installing version 4.10.3 of pymobiledevice3, do I need to once again run 'pip install SideJITServer' because that is still on version 1.3.1 and hasn't been recompiled after the installation of (assuming its independent of) pymobiledevice3 to version 4.10.3

Hope you can still help.

Thanks, in advance.

**Comment by ColinToft** [comment] 2024-06-23 04:44
Hi @yohu123,

No I didn't end up running the pip install again, after upgrading pymobiledevice3 I ended up getting a different error. Maybe try restarting the computer and phone again to see if that helps? Do you see any errors in the output from SideJITServer? Originally I was getting the error that @Bomen9 mentioned:

DeprecationWarning: There is no current event loop
loop = asyncio.get_event_loop()

But after upgrading pymobiledevice3 I didn't get that anymore (I decided to try upgrading pymobiledevice3 because I saw they had fixed this error in later versions).

**Comment by yohu123** [comment] 2024-06-24 12:53
Hi @ColinToft,

I restarting the computer and phone again but that didn't help.

Also, I too stopped getting the "DeprecationWarning: There is no current event loop" error after upgrading pymobiledevice3 to version 4.10.3

But still I get the notorious '{ERROR":"Could not find device!"}' message in Safari when I access the URL 'http://192.168.31.201:8080' listed in PowerShell by the SideJITServer as well as in the Shortcut.

I feel I am really close to solving this and hope either you or @nythepegasus can help us all out.

The following is the output of the PowerShell execution, after redacting the UDID:
-------------------------------------------------------------------------------------
PS C:\Windows\system32> cd ~\Desktop\SideJITServer
PS C:\Users\yohan\Desktop\SideJITServer> python -m venv venv
PS C:\Users\yohan\Desktop\SideJITServer> .\venv\Scripts\Activate.ps1
(venv) PS C:\Users\yohan\Desktop\SideJITServer> SideJITServer --pair
Attempting to pair to a device! (Ctrl+C to stop)
[<PlistUsbmuxLockdownClient ID:0000XXXX-00XXXXXXXXXXXXXX VERSION:17.5.1 TYPE:iPhone15,4 PAIRED:True>]
Continue? [y/N]: y
INFO:     Started server process [3004]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:49151 (Press CTRL+C to quit)
INFO:     127.0.0.1:59175 - "GET / HTTP/1.1" 200 OK
Registration of service SideJITServer._http._tcp.local. in progress...
Service SideJITServer._http._tcp.local. registered
 * Serving Flask app 'SideJITServer'
 * Debug mode: off
INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.31.201:8080
INFO:werkzeug:Press CTRL+C to quit
INFO:werkzeug:192.168.31.53 - - [24/Jun/2024 18:15:57] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.31.53 - - [24/Jun/2024 18:15:57] "GET /favicon.ico HTTP/1.1" 308 -
INFO:werkzeug:192.168.31.53 - - [24/Jun/2024 18:16:22] "GET /0000XXXX-00XXXXXXXXXXXXXX/ HTTP/1.1" 200 -
INFO:werkzeug:192.168.31.53 - - [24/Jun/2024 18:16:22] "GET /0000XXXX-00XXXXXXXXXXXXXX/ HTTP/1.1" 200 -
-------------------------------------------------------------------------------------

**Comment by lienting885** [comment] 2024-06-24 13:08
Hey,I also encountered these errors. But when I updated pymobiledevice3, I got very different results.
It keeps looping this:
‘
WARNING:pymobiledevice3.tunneld:[mobdev2-00008101-001E39000122001E-2408:821a:4736:2bb0:1402:6369:7395:2d3b%0] failed to start CoreDeviceTunnelProxy - skipping
’

**Comment by lienting885** [comment] 2024-06-24 13:09
Hey,I also encountered these errors. But when I updated pymobiledevice3, I got very different results.
It keeps looping this:
`WARNING:pymobiledevice3.tunneld:[mobdev2-00008101-001E39000122001E-2408:821a:4736:2bb0:1402:6369:7395:2d3b%0]` failed to start CoreDeviceTunnelProxy - skipping`

**Comment by lienting885** [comment] 2024-06-24 13:09
Hey,I also encountered these errors. But when I updated pymobiledevice3, I got very different results.
It keeps looping this:
`WARNING:pymobiledevice3.tunneld:[mobdev2-00008101-001E39000122001E-2408:821a:4736:2bb0:1402:6369:7395:2d3b%0] failed to start CoreDeviceTunnelProxy - skipping`

**Comment by ColinToft** [comment] 2024-06-24 13:59
@yohu123 OK this is very strange... I don’t see any actual error messages in this log as far as I can tell. Just wanted to double check that you have plugged your phone into the computer, made it a trusted device by entering the password on the phone, your phone shows up in iTunes or similar, and you're keeping it connected when running the SideJIT shortcut, and using the correct address in the shortcut?

Otherwise I have to say I'm not really sure what could be causing this.

**Comment by ColinToft** [comment] 2024-06-24 13:59
> Hey,I also encountered these errors. But when I updated pymobiledevice3, I got very different results.
> 
> It keeps looping this:
> 
> `WARNING:pymobiledevice3.tunneld:[mobdev2-00008101-XXXXXXXXXXXXXX-XXXX:XXXX:4736:2bb0:XXXX:XXXX:XXXX:2d3b%0] failed to start CoreDeviceTunnelProxy - skipping`

Hey @lienting885, this looks like the message I had before updating my iOS to >= 17.4. What version is your iOS right now?

**Comment by lienting885** [comment] 2024-06-24 14:02
> > Hey,I also encountered these errors. But when I updated pymobiledevice3, I got very different results.
> > It keeps looping this:
> > `WARNING:pymobiledevice3.tunneld:[mobdev2-00008101-XXXXXXXXXXXXXX-XXXX:XXXX:4736:2bb0:XXXX:XXXX:XXXX:2d3b%0] failed to start CoreDeviceTunnelProxy - skipping`
> 
> Hey @lienting885, this looks like the message I had before updating my iOS to >= 17.4. What version is your iOS right now?

iOS 17.2.1

**Comment by ColinToft** [comment] 2024-06-24 14:08
> > > Hey,I also encountered these errors. But when I updated pymobiledevice3, I got very different results.
> 
> > > It keeps looping this:
> 
> > > `WARNING:pymobiledevice3.tunneld:[mobdev2-00008101-XXXXXXXXXXXXXX-XXXX:XXXX:4736:2bb0:XXXX:XXXX:XXXX:2d3b%0] failed to start CoreDeviceTunnelProxy - skipping`
> 
> > 
> 
> > Hey @lienting885, this looks like the message I had before updating my iOS to >= 17.4. What version is your iOS right now?
> 
> 
> 
> iOS 17.2.1

Ok, I think that's probably your issue. I would recommend updating your iOS, that is what fixed the issue for me. pymobiledevice3 changes how it handles the tunnel for devices with iOS 17.4 and above.

**Comment by yohu123** [comment] 2024-06-24 14:15
> @yohu123 OK this is very strange... I don’t see any actual error messages in this log as far as I can tell. Just wanted to double check that you have plugged your phone into the computer, made it a trusted device by entering the password on the phone, your phone shows up in iTunes or similar, and you're keeping it connected when running the SideJIT shortcut, and using the correct address in the shortcut?
> 
> Otherwise I have to say I'm not really sure what could be causing this.

Yes to all of the above. If you see my output of my PowerShell session, you will notice that it first detects my iPhone is connected. After I type ‘y’ and hit enter, it proceeds with the debugging commands. Notice that no errors are listed at any time. But when I paste the ‘http’ URL in Safari on my iPhone while it’s still connected via USB to my laptop, it gives the main error. The same error appears in the SideJITServer shortcut after confirming that the URL and UDID listed in Powershell are correct. What next?

**Comment by ColinToft** [comment] 2024-06-25 17:24
Hi @yohu123,
I'm really sorry to hear you're still having errors. Unfortunately I'm stuck here too. I'm not sure what to try next, as I don’t really know anything about this code base so it's hard for me to suggest next steps. Maybe try the troubleshooting steps in #59 if you haven't already, or if JIT is very important you could try upgrading to the iOS 18 beta and see if it works there (although that does have risks too). Hopefully @nythepegasus may have some more insights on troubleshooting this error. Sorry I couldn't be more help, I hope you are able to resolve this issue! I'll let you know if I think of anything else you could try.

**Comment by yohu123** [comment] 2024-06-26 09:41
Hi @ColinToft,

I’ve gone through not only the troubleshooting steps in #59 but have also gone back and forth the entire instructions just to ensure I haven’t missed anything. 

When you ‘I’m stuck here too’, do you mean that you haven’t yet successfully been able to run the SideJITServer shortcut and thus have been unsuccessful in enabling JIT on your iOS/iPadOS device?

If the above is true, then I wonder if anyone has been successful in enabling JIT on an iPhone 15 (or later model) running iOS 17.5.1 using SideJITServer. 

@nythepegasus please help!

**Comment by ColinToft** [comment] 2024-06-26 12:12
>
> When you ‘I’m stuck here too’, do you mean that you haven’t yet successfully been able to run the SideJITServer shortcut and thus have been unsuccessful in enabling JIT on your iOS/iPadOS device?
> 

Hi @yohu123 ,

Sorry, by that I meant I'm stuck in terms of offering more advice for your current situation. It's unfortunate that there's no other error messages that might be able to help narrow down the problem. The steps that I mentioned did get  the shortcut working for me.

**Comment by Dr-cdfg** [comment] 2024-07-16 15:09
Guys, try running those scripts with administrator privileges in PowerShell.

**Comment by yohu123** [comment] 2024-07-17 03:40
> Guys, try running those scripts with administrator privileges in PowerShell.

Hi @Dr-cdfg ,

I have always run all scripts in PowerShell as administrator only. Anyways, this thread can be closed from my side as:

1) You cannot enable Virtualization on iPhones. 
2) I have used the AltJIT method to enable JIT for DolphiniOS which works just fine. 

Thanks.

**Comment by nythepegasus** [comment] 2024-08-17 11:24
Hello everyone, sorry for all the issues and silence. I hope these issues have been resolved in the latest 1.3.2/1.3.3 but if not definitely reping me or open this issue again. I'm definitely easier to reach on the Discord than here for support.

**Closed by nythepegasus** 2024-08-17 11:24 UTC

**Comment by EpicLPer** [comment] 2024-09-15 20:37
Heya @nythepegasus, I'm not sure if the connection without USB is working as it should, or maybe I'm doing something wrong ^^"

When I try to enable JIT completely wireless (no USB connetion to PC) I'm getting an error `Invalid path or could not find device`, on SideJITServer I'm getting a 404 error whenever I press the shortcut.  
As soon as I connect my iPhone via USB and restart SideJITServer once everything starts working just fine again.

Is there anything I can try to fix this? I'm currently on the latest iOS 18 beta.

**Comment by LoganWolfie** [comment] 2024-09-26 02:31
> x

Same here, I try to do it wirelessly and it gives me the same error.
