### ISSUE TITLE
Could not find device

### ISSUE THREAD

**Issue by onlyzyz** [nythepegasus/SideJITServer#5] opened 2024-03-29 06:07 UTC
1. On Win11, Python 3.12, Windows Terminal(admin) run:
`pip3 install SideJITServer`
2. On iPhone 13 pro iOS 17.0 connet WiFi to computer hotspot, get the shortcut and input UDID+http://192.168.73.47:8080
3. On Terminal(admin) run
`SideJITServer -d`
4. run the shortcut, the output are:

![image](https://github.com/nythepegasus/SideJITServer/assets/127100328/a01bd7b2-4b14-48c0-8290-af6603f78954)

![image](https://github.com/nythepegasus/SideJITServer/assets/127100328/d7cd38b1-804b-419f-b201-49e41ea04e2e)

**Comment by WesleyBryie** [comment] 2024-03-31 16:49
The tunnel is shutting down because it cannot bind to port 49151. Please ensure that you are running SideJITServer in an _**Administrator**_ PowerShell, and that you have no other instance of pymobiledevice3/SideJITServer running.

**Comment by onlyzyz** [comment] 2024-04-01 00:58
> The tunnel is shutting down because it cannot bind to port 49151. Please ensure that you are running SideJITServer in an _**Administrator**_ PowerShell, and that you have no other instance of pymobiledevice3/SideJITServer running.

I checked it out again, do running SideJITServer in an Administrator PowerShell, and do no have other instance of pymobiledevice3/SideJITServer. 
I killed 49151 but it still have the same error. Could it be a bug here?

![image](https://github.com/nythepegasus/SideJITServer/assets/127100328/e3dd20a3-c373-4a5e-b878-31fcc55589fe)

**Comment by onlyzyz** [comment] 2024-04-01 03:49
is it possbile that this program already used port 49151 before? you can see it on my screenshot:
"INFO:Uvicorn running on http://127.0.0.1:49151 (Press CTRL+C to quit)"

**Comment by WesleyBryie** [comment] 2024-04-01 03:53
> is it possbile that this program already used port 49151 before? you can see it on my screenshot:
> "INFO:Uvicorn running on http://127.0.0.1:49151 (Press CTRL+C to quit)"

So the program is only supposed to bind to port 49151 once. Could you please restart your machine to see if that helps, and could you please translate the non-english language (I think its Chinese) in the first screenshot in the line with (Errno 10048).

**Comment by onlyzyz** [comment] 2024-04-01 05:45
> > is it possbile that this program already used port 49151 before? you can see it on my screenshot:
> > "INFO:Uvicorn running on http://127.0.0.1:49151 (Press CTRL+C to quit)"
> 
> So the program is only supposed to bind to port 49151 once. Could you please restart your machine to see if that helps, and could you please translate the non-english language (I think its Chinese) in the first screenshot in the line with (Errno 10048).

I've tried restart my computer but it still have the same error.
Yes it's Chinese. Non-english language in English(full text): "[Errno 10048]error while attempting to bind on address('127.0.0.1'，49151):**Only one usage of each socket address (protocol/network address/port) is normally permitted"**.
I think I will try create trusted tunnel by using pymobiledevice3 to see if there were something missed or not.

**Comment by onlyzyz** [comment] 2024-04-01 06:13
`python -m pymobiledevice3 remote tunneld`
then install a driver
and  it shows:
![image](https://github.com/nythepegasus/SideJITServer/assets/127100328/e8e532fd-e8d4-4468-88d6-c7bb26993a7b)
I think there are somthing to do with pymobiledevice3, i will ask doronz88

**Comment by WesleyBryie** [comment] 2024-04-01 19:01
This does look alot like a pymd3 error, you should mention this issue in the issue you create on the pymobiledevice3 github if you make one.

**Comment by sirpeep** [comment] 2024-04-03 00:31
having same issue, triple checked the udid was correct and still dont know why its acting up. It shows up on itunes and I can pair it correctly, just whenever I run the shortcut it says no device found. And in the logs of powershell the request went through with code 200.

**Comment by onlyzyz** [comment] 2024-04-03 06:28
@WesleyBryie @sirpeep 
update: 
I think this could be iDevice not connected
`pymobiledevice3 remote browse`
![image](https://github.com/nythepegasus/SideJITServer/assets/127100328/07a0a16c-1554-4d10-8e09-9c2db8b6d551)
but i still don't know how to solve this problem

**Comment by WesleyBryie** [comment] 2024-04-03 06:39
What device do you have, is it connected over USB or are you attempting a WiFi connection, have you tried other USB cables, and are you trusting the computer?

**Comment by onlyzyz** [comment] 2024-04-03 07:41
iPhone13 pro iOS 17.0, Win11 Python 3.12
connected both WiFi and USB
i'll try another USB cables(but on iTunes it shows my iPhone). 
already trusted the computer
BTW, `SideJITServer -y` recognized my iPhone
![PixPin_2024-04-03_15-41-18](https://github.com/nythepegasus/SideJITServer/assets/127100328/b62d2d6f-99b5-4db9-b8db-e7c4f3966d8e)

**Comment by sirpeep** [comment] 2024-04-03 11:59
> What device do you have, is it connected over USB or are you attempting a WiFi connection, have you tried other USB cables, and are you trusting the computer?

i’m using the iphone 13 mini, using usb as i couldn’t figure out how to do it on wifi😭. I tried 2 different cables and ports on my computer and they connected to itunes just fine, and it paired with my phone when doing SideJITServer -y. I press trust and put in my password every time.

**Comment by TYJTYYZTYJRYRUYR6** [comment] 2024-04-08 01:06
I found a fix by installing the latest version of pymobiledevice, by using the command `brew install openssl@3 
python3 -m pip install -U pymobiledevice3==3.3.0`. In terminal, by doing this I get past the error... but dolpinios crashes after enabling JIT, hopefully this is just a problem for me. hope this helps.

**Comment by sirpeep** [comment] 2024-04-08 01:15
I’ll try this tomorrow, thanks :)

**Comment by FlMihai** [comment] 2024-04-08 10:58
> I found a fix by installing the latest version of pymobiledevice, by using the command `brew install openssl@3 python3 -m pip install -U pymobiledevice3==3.3.0`. In terminal, by doing this I get past the error... but dolpinios crashes after enabling JIT, hopefully this is just a problem for me. hope this helps.

I can confirm that using 3.3.0 version works, thakns :) also to get Dolphin working on iOS 17 you need to use the latest version, not the one available on the Dolphin page but the version from their github.

**Comment by Clyxos** [comment] 2024-04-08 19:54
Ensuring that I had the right pymobiledevice3 actually fixed it for me too. Thanks!

**Comment by sirpeep** [comment] 2024-04-09 21:35
this might be a completely unrelated issue but now I'm getting this error:
![image](https://github.com/nythepegasus/SideJITServer/assets/98962692/ed1834d0-5d5e-44da-b7c1-6bf0069ee5ed)
It happens when I do `SideJITServer -d`. It says error while attempting to bind on address 127.0.0.1:49151. Not sure whats causing it because when I do `netstat -ano | findstr :49151` it only says its python.
When I do ctrl + c and the netstat command again, it says there's no processes, meaning the process using the port is SideJITServer.

**Comment by Felitendo** [comment] 2024-04-11 17:05
> I found a fix by installing the latest version of pymobiledevice, by using the command `brew install openssl@3 python3 -m pip install -U pymobiledevice3==3.3.0`. In terminal, by doing this I get past the error... but dolpinios crashes after enabling JIT, hopefully this is just a problem for me. hope this helps.

THIS HELPED, thank you soo much <3

**Comment by onlyzyz** [comment] 2024-04-14 03:40
@sirpeep @WesleyBryie update SideJITServer to 1.3.0 and pymobiledevice3 to 3.4.0, still have problems.

**Comment by QcSamuel** [comment] 2024-04-20 00:47
using windows 11 tried using venv same error with the only one usage on port, tried with the recommended pymobiledevice3 version and the latest one

**Comment by QcSamuel** [comment] 2024-05-04 01:01
@onlyzyz did you find a fix for this ? (error while attempting to bind on address('127.0.0.1'，49151):Only one usage of each socket address (protocol/network address/port) is normally permitted".)

**Comment by SeanD6091** [comment] 2024-05-19 19:04
Anyone have any other fixes, because I've tried everything under this issue and nothing has worked

**Comment by onlyzyz** [comment] 2024-05-20 07:58
> @onlyzyz did you find a fix for this ? (error while attempting to bind on address('127.0.0.1'，49151):Only one usage of each socket address (protocol/network address/port) is normally permitted".)

nope.

**Comment by micro2547** [comment] 2024-05-22 00:21
im in venv and i ran the exact commands said in here and nothing works.

**Comment by micro2547** [comment] 2024-05-22 00:26
im on an iphone 13 running 17.4.1, and it keeps saying when i run `sidejitserver -y` or `sidejitserver --pair` that it's an iphone 14.

**Closed** 2024-08-17 11:19 UTC
